# Generated by Django 4.0.3 on 2022-05-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_moon'),
    ]

    operations = [
        migrations.AddField(
            model_name='moon',
            name='orbital_period',
            field=models.FloatField(default=0),
        ),
    ]
