# Generated by Django 4.0.3 on 2022-05-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_moon_orbital_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mineral', models.CharField(choices=[('Mg', 'Magnesium'), ('Al', 'Aluminium'), ('Ti', 'Titanium'), ('Fe', 'Iron'), ('Cu', 'Copper'), ('W', 'Tungsten')], max_length=2)),
            ],
        ),
    ]
