# Generated by Django 4.0.3 on 2022-05-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='resources',
            field=models.ManyToManyField(to='main_app.resource'),
        ),
    ]
